// Code generated by goctl. DO NOT EDIT.
package types

type FileUploadRequest struct {
	AppName  string `path:"AppName"`
	TypeName string `path:"TypeName"`
}

type FileUploadResponse struct {
	Data []FileUpload `json:"data"`
}

type FileUpload struct {
	FileId       int64  `json:"file_id"`
	DownloadPath string `json:"download_path"`
	DiskPath     string `json:"disk_path"`
}

type FileDownloadRequest struct {
	AppName  string `path:"AppName"`
	TypeName string `path:"TypeName"`
	FileName string `path:"FileName"`
}

type FileDownloadResponse struct {
}
